import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { vocabularyDecksData } from "../src/data/vocabularyDecksData.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Real curated vocabulary data bank organized by category and theme
const decksContent = {
  "common-1000": [
    { word: "achieve", ipa: "/əˈtʃiːv/", type: "verb", level: "B1", meaning: "Đạt được, hoàn thành mục tiêu", example: "She worked diligently to achieve high scores.", example_vi: "Cô ấy đã học chăm chỉ để đạt điểm cao.", collocations: "achieve success, achieve a goal", synonyms: "accomplish, attain" },
    { word: "benefit", ipa: "/ˈben.ɪ.fɪt/", type: "noun / verb", level: "A2", meaning: "Lợi ích, được hưởng lợi", example: "Regular exercise brings numerous health benefits.", example_vi: "Tập thể dục đều đặn đem lại nhiều lợi ích sức khỏe.", collocations: "mutual benefit, reap benefits", synonyms: "advantage, profit" },
    { word: "challenge", ipa: "/ˈtʃæl.ɪndʒ/", type: "noun / verb", level: "B1", meaning: "Thử thách, thách thức", example: "Overcoming fear is the ultimate challenge.", example_vi: "Vượt qua nỗi sợ hãi là thử thách lớn nhất.", collocations: "face a challenge, pose a challenge", synonyms: "obstacle, hurdle" },
    { word: "discover", ipa: "/dɪˈskʌv.ər/", type: "verb", level: "A2", meaning: "Khám phá, phát hiện ra điều mới", example: "Researchers discovered an effective new vaccine.", example_vi: "Các nhà nghiên cứu đã phát hiện ra loại vắc xin mới hiệu quả.", collocations: "discover the truth, discover talent", synonyms: "uncover, find" },
    { word: "encourage", ipa: "/ɪnˈkʌr.ɪdʒ/", type: "verb", level: "B1", meaning: "Động viên, khuyến khích", example: "My mentor encouraged me to study abroad.", example_vi: "Người cố vấn đã khuyến khích tôi đi du học.", collocations: "encourage someone to do something", synonyms: "inspire, motivate" },
    { word: "focus", ipa: "/ˈfəʊ.kəs/", type: "verb / noun", level: "A2", meaning: "Tập trung, trọng tâm", example: "Please focus on finishing your assignment today.", example_vi: "Hãy tập trung vào việc hoàn thành bài tập hôm nay.", collocations: "focus attention on, sharp focus", synonyms: "concentrate, pinpoint" },
    { word: "generate", ipa: "/ˈdʒen.ə.reɪt/", type: "verb", level: "B2", meaning: "Tạo ra, sản sinh ra", example: "Wind turbines generate clean renewable electricity.", example_vi: "Tua bin gió tạo ra điện năng tái tạo sạch.", collocations: "generate revenue, generate interest", synonyms: "produce, create" },
    { word: "habit", ipa: "/ˈhæb.ɪt/", type: "noun", level: "A1", meaning: "Thói quen tốt hoặc xấu", example: "Reading books every night is a great habit.", example_vi: "Đọc sách mỗi tối là một thói quen tuyệt vời.", collocations: "form a habit, break a habit", synonyms: "routine, custom" },
    { word: "improve", ipa: "/ɪmˈpruːv/", type: "verb", level: "A2", meaning: "Cải thiện, tiến bộ", example: "Daily shadowing practice will improve your accent.", example_vi: "Luyện shadowing mỗi ngày sẽ cải thiện giọng phát âm của bạn.", collocations: "improve quality, improve skills", synonyms: "enhance, boost" },
    { word: "journey", ipa: "/ˈdʒɜː.ni/", type: "noun", level: "A2", meaning: "Hành trình, chuyến đi", example: "Mastering a foreign language is an exciting journey.", example_vi: "Làm chủ một ngoại ngữ là một hành trình thú vị.", collocations: "safe journey, life journey", synonyms: "voyage, trip" },
    { word: "knowledge", ipa: "/ˈnɒl.ɪdʒ/", type: "noun", level: "A2", meaning: "Kiến thức, sự hiểu biết", example: "She has a vast knowledge of English literature.", example_vi: "Cô ấy có vốn kiến thức sâu rộng về văn học Anh.", collocations: "acquire knowledge, deep knowledge", synonyms: "wisdom, expertise" },
    { word: "opportunity", ipa: "/ˌɒp.əˈtʃuː.nə.ti/", type: "noun", level: "B1", meaning: "Cơ hội, thời cơ tốt", example: "This internship is a fantastic career opportunity.", example_vi: "Kỳ thực tập này là một cơ hội nghề nghiệp tuyệt vời.", collocations: "grab an opportunity, golden opportunity", synonyms: "chance, opening" },
    { word: "protect", ipa: "/prəˈtekt/", type: "verb", level: "A2", meaning: "Bảo vệ, che chở", example: "Sunscreen helps protect your skin from UV rays.", example_vi: "Kem chống nắng giúp bảo vệ làn da của bạn khỏi tia UV.", collocations: "protect environment, protect privacy", synonyms: "safeguard, defend" },
    { word: "quality", ipa: "/ˈkwɒl.ə.ti/", type: "noun / adj", level: "A2", meaning: "Chất lượng, phẩm chất", example: "High quality products always build customer trust.", example_vi: "Sản phẩm chất lượng cao luôn tạo dựng niềm tin nơi khách hàng.", collocations: "quality of life, premium quality", synonyms: "standard, excellence" },
    { word: "remember", ipa: "/rɪˈmem.bər/", type: "verb", level: "A1", meaning: "Ghi nhớ, nhớ lại", example: "Remember to review your flashcards before bedtime.", example_vi: "Hãy nhớ ôn lại thẻ từ vựng trước khi đi ngủ.", collocations: "remember clearly, remember to do", synonyms: "recall, recollect" },
    { word: "solution", ipa: "/səˈluː.ʃən/", type: "noun", level: "B1", meaning: "Giải pháp, phương án giải quyết", example: "We need an innovative solution to reduce urban traffic.", example_vi: "Chúng ta cần một giải pháp đột phá để giảm ùn tắc đô thị.", collocations: "find a solution, practical solution", synonyms: "answer, remedy" },
    { word: "talent", ipa: "/ˈtæl.ənt/", type: "noun", level: "B1", meaning: "Tài năng, năng khiếu", example: "He showed an extraordinary talent for playing violin.", example_vi: "Cậu ấy bộc lộ tài năng xuất chúng trong việc chơi vĩ cầm.", collocations: "natural talent, showcase talent", synonyms: "gift, ability" },
    { word: "unique", ipa: "/juːˈniːk/", type: "adj", level: "B2", meaning: "Độc đáo, duy nhất", example: "Each fingerprint is completely unique to the individual.", example_vi: "Mỗi dấu vân tay hoàn toàn là duy nhất đối với từng người.", collocations: "unique feature, unique opportunity", synonyms: "distinctive, exclusive" },
    { word: "valuable", ipa: "/ˈvæl.jə.bəl/", type: "adj", level: "B1", meaning: "Có giá trị, quý giá", example: "Her advice proved to be exceptionally valuable.", example_vi: "Lời khuyên của cô ấy đã chứng tỏ là đặc biệt quý giá.", collocations: "valuable experience, valuable asset", synonyms: "precious, priceless" },
    { word: "wonderful", ipa: "/ˈwʌn.də.fəl/", type: "adj", level: "A1", meaning: "Tuyệt vời, kỳ diệu", example: "We had a wonderful weekend in Da Lat.", example_vi: "Chúng tôi đã có một kỳ nghỉ cuối tuần tuyệt vời ở Đà Lạt.", collocations: "wonderful experience, wonderful news", synonyms: "marvelous, fantastic" }
  ],
  "conversation": [
    { word: "Hang out", ipa: "/hæŋ aʊt/", type: "phrasal verb", level: "A2", meaning: "Đi chơi, tụ tập bạn bè", example: "Do you want to hang out at the coffee shop after class?", example_vi: "Bạn có muốn đi cà phê tụ tập sau giờ học không?", collocations: "hang out with friends", synonyms: "chill, socialize" },
    { word: "Catch up", ipa: "/kætʃ ʌp/", type: "phrasal verb", level: "B1", meaning: "Hàn huyên, cập nhật tin tức cho nhau", example: "It has been months, let us grab lunch and catch up!", example_vi: "Đã nhiều tháng rồi, hãy cùng ăn trưa và hàn huyên nào!", collocations: "catch up on news, catch up with someone", synonyms: "reconnect, update" },
    { word: "Under the weather", ipa: "/ˈʌn.dər ðə ˈweð.ər/", type: "idiom", level: "B1", meaning: "Cảm thấy mệt mỏi, không khỏe", example: "I am feeling a bit under the weather today, so I will stay home.", example_vi: "Hôm nay tôi hơi khó ở trong người nên sẽ ở nhà nghỉ ngơi.", collocations: "feel under the weather", synonyms: "sick, unwell" },
    { word: "Piece of cake", ipa: "/piːs əv keɪk/", type: "idiom", level: "A2", meaning: "Dễ như ăn cháo, rất dễ dàng", example: "That TOEIC test was a piece of cake for him.", example_vi: "Bài thi TOEIC đó đối với anh ấy dễ như trở bàn tay.", collocations: "be a piece of cake", synonyms: "effortless, walk in the park" },
    { word: "Break a leg", ipa: "/breɪk ə leɡ/", type: "idiom", level: "B1", meaning: "Chúc may mắn (trước giờ diễn/thi)", example: "You have practiced so hard. Break a leg out there!", example_vi: "Bạn đã luyện tập rất chăm chỉ rồi. Chúc may mắn nhé!", collocations: "wish someone break a leg", synonyms: "good luck" },
    { word: "Hit the books", ipa: "/hɪt ðə bʊks/", type: "idiom", level: "B1", meaning: "Cắm đầu vào học, học bài chăm chỉ", example: "Final exams start tomorrow, time to hit the books!", example_vi: "Kỳ thi học kỳ bắt đầu vào ngày mai rồi, phải cắm đầu vào học thôi!", collocations: "hit the books tonight", synonyms: "cram, study hard" },
    { word: "Call it a day", ipa: "/kɔːl ɪt ə deɪ/", type: "idiom", level: "B1", meaning: "Dừng làm việc nghỉ ngơi cho hôm nay", example: "We have finished ten lessons, let's call it a day.", example_vi: "Chúng ta đã hoàn thành mười bài học rồi, hôm nay dừng ở đây thôi.", collocations: "decide to call it a day", synonyms: "wrap up, finish" },
    { word: "Look forward to", ipa: "/lʊk ˈfɔː.wəd tuː/", type: "phrasal verb", level: "B1", meaning: "Háo hức mong chờ điều gì", example: "I look forward to meeting your family next week.", example_vi: "Tôi rất háo hức mong chờ được gặp gia đình bạn vào tuần tới.", collocations: "look forward to hearing from you", synonyms: "anticipate, eagerly await" },
    { word: "Figure out", ipa: "/ˈfɪɡ.ər aʊt/", type: "phrasal verb", level: "B1", meaning: "Tìm ra lời giải, hiểu ra vấn đề", example: "I cannot figure out how to solve this grammar puzzle.", example_vi: "Tôi chưa thể tìm ra cách giải câu đố ngữ pháp này.", collocations: "figure out a solution", synonyms: "solve, comprehend" },
    { word: "No big deal", ipa: "/nəʊ bɪɡ diːl/", type: "idiom", level: "A2", meaning: "Không sao đâu, không có gì to tát", example: "Thank you for the ride! — No big deal, it was on my way.", example_vi: "Cảm ơn bạn đã cho đi nhờ! — Không có gì đâu, tiện đường mà.", collocations: "make a big deal out of it", synonyms: "not a problem, you're welcome" },
    { word: "Rely on", ipa: "/rɪˈlaɪ ɒn/", type: "phrasal verb", level: "B1", meaning: "Dựa dẫm vào, tin tưởng vào", example: "You can always rely on your study partner for support.", example_vi: "Bạn luôn có thể tin tưởng và dựa vào người bạn cùng học của mình.", collocations: "rely heavily on", synonyms: "depend on, trust" },
    { word: "Turn down", ipa: "/tɜːn daʊn/", type: "phrasal verb", level: "B1", meaning: "Từ chối lời mời/đề xuất; vặn nhỏ âm lượng", example: "He turned down the job offer because the salary was too low.", example_vi: "Anh ấy đã từ chối lời mời làm việc vì mức lương quá thấp.", collocations: "turn down an offer", synonyms: "reject, decline" },
    { word: "Get along with", ipa: "/ɡet əˈlɒŋ wɪð/", type: "phrasal verb", level: "B1", meaning: "Hòa thuận, hợp cạ với ai đó", example: "I get along very well with my new roommates.", example_vi: "Tôi rất hòa thuận và thân thiết với những người bạn cùng phòng mới.", collocations: "get along famously with", synonyms: "be friendly with, harmonize" },
    { word: "Run out of", ipa: "/rʌn aʊt əv/", type: "phrasal verb", level: "A2", meaning: "Hết sạch, cạn kiệt thứ gì đó", example: "Hurry up, we are running out of time before the exam!", example_vi: "Nhanh lên nào, chúng ta sắp hết giờ trước khi vào thi rồi!", collocations: "run out of battery, run out of money", synonyms: "deplete, exhaust" },
    { word: "Keep in touch", ipa: "/kiːp ɪn tʌtʃ/", type: "idiom", level: "A2", meaning: "Giữ liên lạc thường xuyên", example: "Let's exchange emails so we can keep in touch.", example_vi: "Chúng mình hãy trao đổi email để giữ liên lạc nhé.", collocations: "keep in touch with someone", synonyms: "stay connected" }
  ],
  "oxford-3000-a1": [
    { word: "accept", ipa: "/əkˈsept/", type: "verb", level: "A1", meaning: "Chấp nhận, đồng ý nhận", example: "She accepted the scholarship offer immediately.", example_vi: "Cô ấy đã đồng ý nhận học bổng ngay lập tức.", collocations: "accept an invitation, accept responsibility", synonyms: "agree to, receive" },
    { word: "accident", ipa: "/ˈæk.sɪ.dənt/", type: "noun", level: "A1", meaning: "Tai nạn, sự cố bất ngờ", example: "Drive carefully to prevent road accidents.", example_vi: "Hãy lái xe cẩn thận để phòng tránh tai nạn giao thông.", collocations: "by accident, fatal accident", synonyms: "crash, mishap" },
    { word: "activity", ipa: "/ækˈtɪv.ə.ti/", type: "noun", level: "A1", meaning: "Hoạt động sinh hoạt/học tập", example: "Outdoor activities help reduce stress.", example_vi: "Các hoạt động ngoài trời giúp giải tỏa căng thẳng.", collocations: "leisure activity, physical activity", synonyms: "action, pastime" },
    { word: "advice", ipa: "/ədˈvaɪs/", type: "noun", level: "A1", meaning: "Lời khuyên, sự chỉ dẫn", example: "Ask your teacher for advice on learning vocabulary.", example_vi: "Hãy hỏi giáo viên lời khuyên về cách học từ vựng.", collocations: "give advice, take someone's advice", synonyms: "guidance, counsel" },
    { word: "afraid", ipa: "/əˈfreɪd/", type: "adj", level: "A1", meaning: "Sợ hãi, e ngại", example: "Do not be afraid of making mistakes when speaking English.", example_vi: "Đừng e ngại việc mắc lỗi khi nói tiếng Anh.", collocations: "afraid of the dark, afraid to speak", synonyms: "scared, frightened" },
    { word: "allow", ipa: "/əˈlaʊ/", type: "verb", level: "A1", meaning: "Cho phép ai làm gì", example: "The library does not allow eating inside.", example_vi: "Thư viện không cho phép ăn uống bên trong.", collocations: "allow someone to do something", synonyms: "permit, authorize" },
    { word: "amazing", ipa: "/əˈmeɪ.zɪŋ/", type: "adj", level: "A1", meaning: "Kinh ngạc, tuyệt vời", example: "She made amazing progress in only three months.", example_vi: "Cô ấy đã tiến bộ kinh ngạc chỉ trong vòng ba tháng.", collocations: "amazing achievement, amazing view", synonyms: "astonishing, wonderful" },
    { word: "arrive", ipa: "/əˈraɪv/", type: "verb", level: "A1", meaning: "Đến nơi, cập bến", example: "The train will arrive at platform three in five minutes.", example_vi: "Chuyến tàu sẽ đến sân ga số 3 trong 5 phút nữa.", collocations: "arrive on time, arrive at airport", synonyms: "reach, get to" },
    { word: "become", ipa: "/bɪˈkʌm/", type: "verb", level: "A1", meaning: "Trở thành, biến thành", example: "He studied hard to become a qualified doctor.", example_vi: "Anh ấy đã học chăm chỉ để trở thành một bác sĩ giỏi.", collocations: "become famous, become aware", synonyms: "turn into, grow" },
    { word: "believe", ipa: "/bɪˈliːv/", type: "verb", level: "A1", meaning: "Tin tưởng, tin rằng", example: "Believe in yourself and your ability to succeed.", example_vi: "Hãy tin vào bản thân và khả năng thành công của bạn.", collocations: "believe in oneself, firmly believe", synonyms: "trust, have faith in" },
    { word: "borrow", ipa: "/ˈbɒr.əʊ/", type: "verb", level: "A1", meaning: "Vay mượn từ ai đó", example: "Can I borrow your bilingual dictionary for today?", example_vi: "Tôi có thể mượn cuốn từ điển song ngữ của bạn hôm nay không?", collocations: "borrow money, borrow books", synonyms: "take on loan" },
    { word: "careful", ipa: "/ˈkeə.fəl/", type: "adj", level: "A1", meaning: "Cẩn thận, thận trọng", example: "Be careful when crossing the crowded street.", example_vi: "Hãy cẩn thận khi băng qua con phố đông đúc.", collocations: "be careful with, careful attention", synonyms: "cautious, attentive" },
    { word: "celebrate", ipa: "/ˈsel.ə.breɪt/", type: "verb", level: "A1", meaning: "Ăn mừng, kỷ niệm", example: "We celebrated passing the IELTS exam with a dinner party.", example_vi: "Chúng tôi đã ăn mừng việc đỗ kỳ thi IELTS bằng một bữa tiệc tối.", collocations: "celebrate a birthday, celebrate victory", synonyms: "commemorate, observe" },
    { word: "choose", ipa: "/tʃuːz/", type: "verb", level: "A1", meaning: "Lựa chọn, chọn lọc", example: "Choose words that accurately reflect your thoughts.", example_vi: "Hãy chọn những từ phản ánh chính xác suy nghĩ của bạn.", collocations: "choose wisely, choose between", synonyms: "select, pick" },
    { word: "decide", ipa: "/dɪˈsaɪd/", type: "verb", level: "A1", meaning: "Quyết định", example: "I decided to practice English shadowing every morning.", example_vi: "Tôi đã quyết định luyện tập shadowing tiếng Anh vào mỗi buổi sáng.", collocations: "decide to do something, decide on a plan", synonyms: "resolve, determine" }
  ],
  "oxford-3000-a2": [
    { word: "admire", ipa: "/ədˈmaɪər/", type: "verb", level: "A2", meaning: "Ngưỡng mộ, khâm phục", example: "I deeply admire her determination to master English.", example_vi: "Tôi vô cùng ngưỡng mộ sự quyết tâm làm chủ tiếng Anh của cô ấy.", collocations: "admire someone for something", synonyms: "respect, look up to" },
    { word: "admit", ipa: "/ədˈmɪt/", type: "verb", level: "A2", meaning: "Thừa nhận, thú nhận lỗi lầm", example: "He admitted that he had made a spelling mistake.", example_vi: "Anh ấy đã thừa nhận rằng mình đã mắc một lỗi chính tả.", collocations: "admit defeat, admit mistakes", synonyms: "confess, acknowledge" },
    { word: "advantage", ipa: "/ədˈvɑːn.tɪdʒ/", type: "noun", level: "A2", meaning: "Lợi thế, ưu điểm", example: "Fluency in English gives you a competitive advantage.", example_vi: "Sự lưu loát tiếng Anh mang lại cho bạn một lợi thế cạnh tranh lớn.", collocations: "take advantage of, distinct advantage", synonyms: "benefit, edge" },
    { word: "adventure", ipa: "/ədˈven.tʃər/", type: "noun", level: "A2", meaning: "Chuyến phiêu lưu, mạo hiểm", example: "Traveling solo across Southeast Asia was an exciting adventure.", example_vi: "Đi du lịch một mình qua Đông Nam Á là một chuyến phiêu lưu kỳ thú.", collocations: "sense of adventure, embark on an adventure", synonyms: "journey, quest" },
    { word: "afford", ipa: "/əˈfɔːd/", type: "verb", level: "A2", meaning: "Có đủ khả năng chi trả tiền bạc/thời gian", example: "With this discount, students can easily afford the course.", example_vi: "Với mức giảm giá này, sinh viên có thể dễ dàng chi trả cho khóa học.", collocations: "cannot afford to, afford the cost", synonyms: "manage, bear the cost" },
    { word: "ancient", ipa: "/ˈeɪn.ʃənt/", type: "adj", level: "A2", meaning: "Cổ xưa, cổ đại", example: "Hoi An is famous for its preserved ancient architecture.", example_vi: "Hội An nổi tiếng với kiến trúc cổ kính được gìn giữ nguyên vẹn.", collocations: "ancient history, ancient civilization", synonyms: "historic, antique" },
    { word: "announce", ipa: "/əˈnaʊns/", type: "verb", level: "A2", meaning: "Thông báo, công bố", example: "The school announced the dates for the upcoming finals.", example_vi: "Trường học đã thông báo ngày thi cho kỳ thi cuối kỳ sắp tới.", collocations: "announce winners, official announcement", synonyms: "declare, broadcast" },
    { word: "apologize", ipa: "/əˈpɒl.ə.dʒaɪz/", type: "verb", level: "A2", meaning: "Xin lỗi ai đó vì điều gì", example: "He apologized for arriving late to the interview.", example_vi: "Anh ấy đã xin lỗi vì đã đến muộn trong buổi phỏng vấn.", collocations: "apologize for doing something, sincere apology", synonyms: "say sorry, make amends" },
    { word: "attract", ipa: "/əˈtrækt/", type: "verb", level: "A2", meaning: "Thu hút, lôi cuốn", example: "The interactive app attracted thousands of enthusiastic learners.", example_vi: "Ứng dụng tương tác đã thu hút hàng nghìn người học nhiệt huyết.", collocations: "attract attention, attract customers", synonyms: "draw, appeal to" },
    { word: "available", ipa: "/əˈveɪ.lə.bəl/", type: "adj", level: "A2", meaning: "Có sẵn, rảnh rỗi", example: "Free practice tests are available on the website.", example_vi: "Các bài thi thử miễn phí luôn có sẵn trên trang web.", collocations: "readily available, available for download", synonyms: "accessible, obtainable" },
    { word: "background", ipa: "/ˈbæk.ɡraʊnd/", type: "noun", level: "A2", meaning: "Bối cảnh, nền tảng học vấn", example: "Students from diverse educational backgrounds joined the seminar.", example_vi: "Sinh viên từ nhiều nền tảng học vấn đa dạng đã tham dự buổi hội thảo.", collocations: "cultural background, background information", synonyms: "heritage, upbringing" },
    { word: "behavior", ipa: "/bɪˈheɪ.vjər/", type: "noun", level: "A2", meaning: "Hành vi, thái độ ứng xử", example: "Polite behavior always leaves a positive impression.", example_vi: "Hành vi lịch thiệp luôn để lại ấn tượng tốt đẹp.", collocations: "good behavior, study human behavior", synonyms: "conduct, demeanor" },
    { word: "brilliant", ipa: "/ˈbrɪl.jənt/", type: "adj", level: "A2", meaning: "Xuất sắc, sáng dạ", example: "She came up with a brilliant idea for the project.", example_vi: "Cô ấy đã nảy ra một ý tưởng xuất sắc cho dự án.", collocations: "brilliant mind, brilliant performance", synonyms: "outstanding, exceptional" },
    { word: "cancel", ipa: "/ˈkæn.səl/", type: "verb", level: "A2", meaning: "Hủy bỏ", example: "The outdoor concert was canceled due to heavy rainfall.", example_vi: "Buổi hòa nhạc ngoài trời đã bị hủy bỏ do mưa lớn.", collocations: "cancel an appointment, cancel a flight", synonyms: "call off, nullify" },
    { word: "confident", ipa: "/ˈkɒn.fɪ.dənt/", type: "adj", level: "A2", meaning: "Tự tin", example: "Practicing pronunciation daily will make you feel confident.", example_vi: "Luyện phát âm mỗi ngày sẽ giúp bạn cảm thấy tự tin.", collocations: "confident speaker, self-confident", synonyms: "assured, self-reliant" }
  ],
  "oxford-3000-b1": [
    { word: "academic", ipa: "/ˌæk.əˈdem.ɪk/", type: "adj / noun", level: "B1", meaning: "Thuộc về học thuật, viện nghiên cứu", example: "The university demands high academic standards.", example_vi: "Trường đại học đòi hỏi các tiêu chuẩn học thuật cao.", collocations: "academic performance, academic research", synonyms: "scholarly, educational" },
    { word: "accurate", ipa: "/ˈæk.jə.rət/", type: "adj", level: "B1", meaning: "Chính xác, chuẩn xác từng chi tiết", example: "Provide an accurate translation of the passage.", example_vi: "Hãy đưa ra một bản dịch chính xác cho đoạn văn.", collocations: "accurate measurement, accurate description", synonyms: "precise, exact" },
    { word: "acquire", ipa: "/əˈkwaɪər/", type: "verb", level: "B1", meaning: "Thu nhận, tiếp thu kiến thức/kỹ năng", example: "Children acquire languages faster than adults.", example_vi: "Trẻ em tiếp thu ngôn ngữ nhanh hơn người lớn.", collocations: "acquire skills, acquire knowledge", synonyms: "gain, attain" },
    { word: "adequate", ipa: "/ˈæd.ə.kwət/", type: "adj", level: "B1", meaning: "Đầy đủ, thỏa đáng cho yêu cầu", example: "Ensure you get adequate rest before taking the test.", example_vi: "Hãy đảm bảo bạn nghỉ ngơi đầy đủ trước khi làm bài thi.", collocations: "adequate preparation, adequate resources", synonyms: "sufficient, ample" },
    { word: "alter", ipa: "/ˈɒl.tər/", type: "verb", level: "B1", meaning: "Thay đổi, biến đổi", example: "Moving to a new city altered his perspective on life.", example_vi: "Chuyển đến thành phố mới đã làm thay đổi góc nhìn cuộc sống của anh ấy.", collocations: "alter plans, alter behavior", synonyms: "change, modify" },
    { word: "analyze", ipa: "/ˈæn.əl.aɪz/", type: "verb", level: "B1", meaning: "Phân tích số liệu/thông tin", example: "The economist analyzed recent market trends carefully.", example_vi: "Nhà kinh tế học đã phân tích kỹ lưỡng các xu hướng thị trường gần đây.", collocations: "analyze data, analyze results", synonyms: "examine, inspect" },
    { word: "apparent", ipa: "/əˈpær.ənt/", type: "adj", level: "B1", meaning: "Rõ ràng, hiển nhiên", example: "It became apparent that practice made a huge difference.", example_vi: "Rõ ràng là việc luyện tập đã tạo nên sự khác biệt to lớn.", collocations: "readily apparent, for no apparent reason", synonyms: "obvious, evident" },
    { word: "approach", ipa: "/əˈprəʊtʃ/", type: "noun / verb", level: "B1", meaning: "Phương pháp tiếp cận; tiếp cận", example: "We adopted a communicative approach to teaching English.", example_vi: "Chúng tôi đã áp dụng phương pháp tiếp cận giao tiếp trong giảng dạy tiếng Anh.", collocations: "take an approach, innovative approach", synonyms: "method, strategy" },
    { word: "appropriate", ipa: "/əˈprəʊ.pri.ət/", type: "adj", level: "B1", meaning: "Thích hợp, phù hợp hoàn cảnh", example: "Wear appropriate clothing for the formal job interview.", example_vi: "Hãy mặc trang phục thích hợp cho buổi phỏng vấn xin việc trang trọng.", collocations: "highly appropriate, appropriate response", synonyms: "suitable, fitting" },
    { word: "aspect", ipa: "/ˈæs.pekt/", type: "noun", level: "B1", meaning: "Khía cạnh, mặt của vấn đề", example: "Pronunciation is a crucial aspect of communication.", example_vi: "Phát âm là một khía cạnh cốt lõi của giao tiếp.", collocations: "key aspect, every aspect of life", synonyms: "facet, dimension" },
    { word: "assume", ipa: "/əˈsjuːm/", type: "verb", level: "B1", meaning: "Giả định, cho rằng", example: "Do not assume that everyone speaks fluent English.", example_vi: "Đừng vội cho rằng ai cũng nói tiếng Anh lưu loát.", collocations: "assume responsibility, reasonable to assume", synonyms: "presume, suppose" },
    { word: "attitude", ipa: "/ˈæt.ɪ.tʃuːd/", type: "noun", level: "B1", meaning: "Thái độ, quan điểm", example: "A positive attitude is vital for overcoming learning setbacks.", example_vi: "Thái độ tích cực là rất quan trọng để vượt qua những khó khăn khi học.", collocations: "positive attitude, change attitude", synonyms: "mindset, outlook" },
    { word: "capable", ipa: "/ˈkeɪ.pə.bəl/", type: "adj", level: "B1", meaning: "Có năng lực, có khả năng làm được", example: "You are fully capable of achieving your target band score.", example_vi: "Bạn hoàn toàn có đủ năng lực để đạt được mục tiêu điểm thi của mình.", collocations: "capable of doing something, highly capable", synonyms: "competent, able" },
    { word: "circumstance", ipa: "/ˈsɜː.kəm.stɑːns/", type: "noun", level: "B1", meaning: "Hoàn cảnh, tình huống thực tế", example: "Under no circumstances should you share your password.", example_vi: "Trong bất kỳ hoàn cảnh nào bạn cũng không nên chia sẻ mật khẩu.", collocations: "under the circumstances, unforeseen circumstances", synonyms: "situation, condition" },
    { word: "communicate", ipa: "/kəˈmjuː.nɪ.keɪt/", type: "verb", level: "B1", meaning: "Giao tiếp, truyền đạt thông điệp", example: "She communicates ideas with clarity and confidence.", example_vi: "Cô ấy truyền đạt các ý tưởng một cách rõ ràng và tự tin.", collocations: "communicate effectively, open communication", synonyms: "convey, express" }
  ],
  "toeic-600": [
    { word: "negotiate", ipa: "/nəˈɡəʊ.ʃi.eɪt/", type: "verb", level: "B2", meaning: "Đàm phán, thương lượng hợp đồng", example: "The procurement team negotiated a 15% price discount.", example_vi: "Đội ngũ thu mua đã đàm phán thành công mức chiết khấu 15%.", collocations: "negotiate a contract, negotiate terms", synonyms: "bargain, haggle" },
    { word: "provision", ipa: "/prəˈvɪʒ.ən/", type: "noun", level: "B2", meaning: "Điều khoản trong văn bản hợp đồng; sự cung cấp", example: "Under the provisions of the lease, pets are strictly prohibited.", example_vi: "Theo các điều khoản của hợp đồng thuê, vật nuôi bị nghiêm cấm.", collocations: "contract provision, make provision for", synonyms: "clause, stipulation" },
    { word: "obligate", ipa: "/ˈɒb.lɪ.ɡeɪt/", type: "verb", level: "B2", meaning: "Bắt buộc, ràng buộc nghĩa vụ pháp lý", example: "Both parties are legally obligated to fulfill the agreement.", example_vi: "Cả hai bên đều có nghĩa vụ pháp lý phải thực hiện thỏa thuận.", collocations: "be obligated to do something, legally obligated", synonyms: "bind, compel" },
    { word: "assurance", ipa: "/əˈʃɔː.rəns/", type: "noun", level: "B2", meaning: "Sự bảo đảm, cam đoan chắc chắn", example: "Management gave assurances that no jobs would be cut.", example_vi: "Ban lãnh đạo đã đưa ra bảo đảm rằng sẽ không cắt giảm nhân sự.", collocations: "give assurance, quality assurance", synonyms: "guarantee, pledge" },
    { word: "reimburse", ipa: "/ˌriː.ɪmˈbɜːs/", type: "verb", level: "B2", meaning: "Hoàn lại tiền, thanh toán lại chi phí công tác", example: "The company will reimburse all travel and lodging expenses.", example_vi: "Công ty sẽ hoàn lại toàn bộ chi phí đi lại và lưu trú.", collocations: "reimburse expenses, prompt reimbursement", synonyms: "refund, repay" },
    { word: "distributor", ipa: "/dɪˈstrɪb.jə.tər/", type: "noun", level: "B1", meaning: "Nhà phân phối hàng hóa", example: "We signed an exclusive agreement with an overseas distributor.", example_vi: "Chúng tôi đã ký hợp đồng độc quyền với một nhà phân phối nước ngoài.", collocations: "authorized distributor, wholesale distributor", synonyms: "supplier, vendor" },
    { word: "inventory", ipa: "/ˈɪn.vən.tər.i/", type: "noun", level: "B1", meaning: "Hàng tồn kho, kiểm kê hàng hóa", example: "The warehouse conducts an annual physical inventory check.", example_vi: "Kho hàng tiến hành kiểm kê thực tế hàng hóa mỗi năm một lần.", collocations: "inventory management, take inventory", synonyms: "stock, merchandise" },
    { word: "prospective", ipa: "/prəˈspek.tɪv/", type: "adj", level: "B2", meaning: "Tiềm năng, triển vọng tương lai", example: "The sales representative delivered a pitch to prospective clients.", example_vi: "Đại diện bán hàng đã thuyết trình trước các khách hàng tiềm năng.", collocations: "prospective client, prospective buyer", synonyms: "potential, future" },
    { word: "commute", ipa: "/kəˈmjuːt/", type: "verb / noun", level: "B1", meaning: "Đi lại hàng ngày giữa nhà và nơi làm việc", example: "He commutes forty-five minutes by subway every workday.", example_vi: "Anh ấy đi lại 45 phút bằng tàu điện ngầm mỗi ngày đi làm.", collocations: "daily commute, commute to work", synonyms: "travel back and forth" },
    { word: "itinerary", ipa: "/aɪˈtɪn.ər.ər.i/", type: "noun", level: "B2", meaning: "Lịch trình chuyến đi, lịch công tác", example: "The travel agent emailed the detailed business itinerary.", example_vi: "Đại lý du lịch đã gửi email lịch trình công tác chi tiết.", collocations: "travel itinerary, flight itinerary", synonyms: "schedule, timetable" },
    { word: "liability", ipa: "/ˌlaɪ.əˈbɪl.ə.ti/", type: "noun", level: "B2", meaning: "Khoản nợ, nghĩa vụ pháp lý gánh chịu", example: "The auditor assessed the firm's total financial liabilities.", example_vi: "Kiểm toán viên đã đánh giá toàn bộ các khoản nợ tài chính của doanh nghiệp.", collocations: "legal liability, asset and liability", synonyms: "obligation, debt" },
    { word: "portfolio", ipa: "/ˌpɔːtˈfəʊ.li.əʊ/", type: "noun", level: "B2", meaning: "Danh mục đầu tư; hồ sơ năng lực dự án", example: "She diversified her investment portfolio with bonds and real estate.", example_vi: "Cô ấy đã đa dạng hóa danh mục đầu tư bằng trái phiếu và bất động sản.", collocations: "investment portfolio, product portfolio", synonyms: "collection, holdings" },
    { word: "consensus", ipa: "/kənˈsen.səs/", type: "noun", level: "B2", meaning: "Sự đồng thuận chung của tập thể", example: "The executive board reached a unanimous consensus on the merger.", example_vi: "Hội đồng quản trị đã đạt được sự đồng thuận nhất trí về việc sáp nhập.", collocations: "reach a consensus, general consensus", synonyms: "agreement, harmony" },
    { word: "headquarters", ipa: "/ˌhedˈkwɔː.təz/", type: "noun", level: "B1", meaning: "Trụ sở chính công ty", example: "The tech giant recently relocated its global headquarters to Singapore.", example_vi: "Tập đoàn công nghệ gần đây đã chuyển trụ sở chính toàn cầu sang Singapore.", collocations: "company headquarters, corporate HQ", synonyms: "main office, base" },
    { word: "warranty", ipa: "/ˈwɒr.ən.ti/", type: "noun", level: "B1", meaning: "Phiếu bảo hành sản phẩm", example: "The laptop comes with a two-year manufacturer warranty.", example_vi: "Chiếc máy tính xách tay đi kèm phiếu bảo hành 2 năm của nhà sản xuất.", collocations: "under warranty, extended warranty", synonyms: "guarantee, bond" }
  ],
  "ielts-band-6-7": [
    { word: "sustainable", ipa: "/səˈsteɪ.nə.bəl/", type: "adj", level: "B2", meaning: "Bền vững, thân thiện với hệ sinh thái", example: "Solar power promotes sustainable economic development.", example_vi: "Năng lượng mặt trời thúc đẩy sự phát triển kinh tế bền vững.", collocations: "sustainable energy, sustainable development", synonyms: "renewable, eco-friendly" },
    { word: "ubiquitous", ipa: "/juːˈbɪk.wɪ.təs/", type: "adj", level: "C1", meaning: "Phổ biến khắp nơi, đâu đâu cũng thấy", example: "Smartphones have become ubiquitous in contemporary society.", example_vi: "Điện thoại thông minh đã trở nên hiện diện ở khắp mọi nơi trong xã hội đương đại.", collocations: "ubiquitous presence, become ubiquitous", synonyms: "omnipresent, pervasive" },
    { word: "detrimental", ipa: "/ˌdet.rɪˈmen.təl/", type: "adj", level: "C1", meaning: "Gây tổn hại, có hại cho sức khỏe/môi trường", example: "Excessive sugar consumption exerts detrimental effects on heart health.", example_vi: "Tiêu thụ đường quá mức gây ra những tác hại khôn lường cho sức khỏe tim mạch.", collocations: "detrimental effect on, detrimental impact", synonyms: "harmful, damaging" },
    { word: "alleviate", ipa: "/əˈliː.vi.eɪt/", type: "verb", level: "C1", meaning: "Làm thuyên giảm, làm dịu bớt nỗi đau/tình trạng", example: "Public transport upgrades aim to alleviate severe city congestion.", example_vi: "Nâng cấp giao thông công cộng nhằm làm thuyên giảm tình trạng tắc đường nghiêm trọng.", collocations: "alleviate poverty, alleviate traffic congestion", synonyms: "ease, relieve, mitigate" },
    { word: "mitigate", ipa: "/ˈmɪt.ɪ.ɡeɪt/", type: "verb", level: "C1", meaning: "Giảm thiểu tác động tiêu cực hoặc rủi ro", example: "Planting mangroves mitigates coastal erosion during storms.", example_vi: "Trồng rừng ngập mặn giúp giảm thiểu xói mòn bờ biển khi có bão.", collocations: "mitigate climate change, mitigate risk", synonyms: "reduce, diminish" },
    { word: "predominant", ipa: "/prɪˈdɒm.ɪ.nənt/", type: "adj", level: "C1", meaning: "Chiếm ưu thế, nổi trội nhất", example: "English remains the predominant international language of science.", example_vi: "Tiếng Anh vẫn là ngôn ngữ quốc tế chủ đạo của giới khoa học.", collocations: "predominant factor, predominant role", synonyms: "dominant, prevailing" },
    { word: "catalyst", ipa: "/ˈkæt.əl.ɪst/", type: "noun", level: "C1", meaning: "Chất xúc tác, nhân tố thúc đẩy thay đổi mạnh mẽ", example: "Technological innovation served as a catalyst for educational transformation.", example_vi: "Sự đổi mới công nghệ đã đóng vai trò là chất xúc tác cho chuyển đổi giáo dục.", collocations: "act as a catalyst, economic catalyst", synonyms: "stimulus, spark" },
    { word: "feasible", ipa: "/ˈfiː.zə.bəl/", type: "adj", level: "B2", meaning: "Khả thi, có thể thực hiện được trong thực tế", example: "The proposed subway expansion is economically and technically feasible.", example_vi: "Đề xuất mở rộng tuyến tàu điện ngầm là khả thi về cả mặt kinh tế và kỹ thuật.", collocations: "feasible solution, financially feasible", synonyms: "viable, workable" },
    { word: "plausible", ipa: "/ˈplɔː.zə.bəl/", type: "adj", level: "C1", meaning: "Hợp lý, đáng tin cậy, có cơ sở", example: "The archaeologist presented a plausible explanation for the monument's alignment.", example_vi: "Nhà khảo cổ học đã đưa ra một lời giải thích hợp lý về hướng căn chỉnh của đài tưởng niệm.", collocations: "plausible explanation, plausible scenario", synonyms: "believable, credible" },
    { word: "lucrative", ipa: "/ˈluː.krə.tɪv/", type: "adj", level: "C1", meaning: "Sinh lợi nhiều, hái ra tiền", example: "Artificial intelligence has evolved into a highly lucrative market.", example_vi: "Trí tuệ nhân tạo đã phát triển thành một thị trường mang lại lợi nhuận khổng lồ.", collocations: "lucrative business, lucrative contract", synonyms: "profitable, rewarding" },
    { word: "manifest", ipa: "/ˈmæn.ɪ.fest/", type: "verb / adj", level: "C1", meaning: "Biểu hiện rõ ràng; biểu lộ ra", example: "Stress frequently manifests as physical exhaustion and insomnia.", example_vi: "Căng thẳng tâm lý thường biểu hiện ra bằng sự kiệt sức thể chất và mất ngủ.", collocations: "manifest itself in, clear manifestation", synonyms: "exhibit, display" },
    { word: "fluctuate", ipa: "/ˈflʌk.tʃu.eɪt/", type: "verb", level: "B2", meaning: "Dao động, biến động liên tục", example: "Export revenues fluctuated substantially throughout the quarters.", example_vi: "Doanh thu xuất khẩu đã biến động đáng kể qua các quý.", collocations: "fluctuate wildly, fluctuate between", synonyms: "oscillate, vary" },
    { word: "inevitable", ipa: "/ɪnˈev.ɪ.tə.bəl/", type: "adj", level: "B2", meaning: "Không thể tránh khỏi, tất yếu xảy ra", example: "Digital automation in manufacturing is practically inevitable.", example_vi: "Tự động hóa số trong sản xuất là điều gần như không thể tránh khỏi.", collocations: "inevitable consequence, inevitable outcome", synonyms: "unavoidable, inescapable" },
    { word: "subsequent", ipa: "/ˈsʌb.sɪ.kwənt/", type: "adj", level: "B2", meaning: "Xảy ra sau đó, tiếp theo sau", example: "The initial study and subsequent experiments confirmed the theory.", example_vi: "Nghiên cứu ban đầu và các thí nghiệm tiếp theo sau đó đã chứng minh lý thuyết.", collocations: "subsequent years, subsequent research", synonyms: "following, succeeding" },
    { word: "fundamental", ipa: "/ˌfʌn.dəˈmen.təl/", type: "adj", level: "B2", meaning: "Cơ bản, cốt lõi, nền tảng", example: "Freedom of speech is a fundamental human right.", example_vi: "Tự do ngôn luận là một quyền con người cơ bản.", collocations: "fundamental difference, fundamental principle", synonyms: "basic, essential" }
  ],
  "lunar-new-year": [
    { word: "Lunar calendar", ipa: "/ˈluː.nər ˈkæl.ɪn.dər/", type: "noun", level: "B1", meaning: "Âm lịch", example: "Vietnamese Tet follows the ancient lunar calendar.", example_vi: "Tết cổ truyền Việt Nam diễn ra theo âm lịch.", collocations: "based on the lunar calendar", synonyms: "moon calendar" },
    { word: "Apricot blossom", ipa: "/ˈeɪ.prɪ.kɒt ˈblɒs.əm/", type: "noun", level: "A2", meaning: "Hoa mai vàng (biểu tượng Tết phương Nam)", example: "Yellow apricot blossoms brighten southern Vietnamese homes during Tet.", example_vi: "Hoa mai vàng rực rỡ bừng sáng những ngôi nhà phương Nam ngày Tết.", collocations: "yellow apricot blossom", synonyms: "ochna blossom" },
    { word: "Peach blossom", ipa: "/piːtʃ ˈblɒs.əm/", type: "noun", level: "A2", meaning: "Hoa đào phai / đào bích (biểu tượng Tết miền Bắc)", example: "Pink peach blossoms signify renewal and good fortune in northern Vietnam.", example_vi: "Hoa đào hồng thắm tượng trưng cho sự sinh sôi và may mắn ở miền Bắc.", collocations: "pink peach blossom branch", synonyms: "cherry blossom" },
    { word: "Kumquat tree", ipa: "/ˈkʌm.kwɒt triː/", type: "noun", level: "A2", meaning: "Cây quất / tắc cảnh ngày Tết", example: "A kumquat tree laden with golden fruit symbolizes prosperity.", example_vi: "Cây quất trĩu quả vàng mọng tượng trưng cho sự thịnh vượng.", collocations: "potted kumquat tree", synonyms: "citrus plant" },
    { word: "Lucky money", ipa: "/ˈlʌk.i ˈmʌn.i/", type: "noun", level: "A1", meaning: "Tiền mừng tuổi, tiền lì xì", example: "Elders give children red envelopes filled with lucky money.", example_vi: "Người lớn trao cho trẻ em những phong bao đỏ chứa tiền mừng tuổi.", collocations: "red envelope with lucky money", synonyms: "li xi" },
    { word: "Square glutinous rice cake", ipa: "/skweər ˈɡluː.tɪ.nəs raɪs keɪk/", type: "noun", level: "B1", meaning: "Bánh chưng", example: "Wrapping square glutinous rice cakes is a sacred family tradition.", example_vi: "Gói bánh chưng xanh là một nét truyền thống gia đình thiêng liêng.", collocations: "traditional Banh Chung", synonyms: "Banh Chung" },
    { word: "Five-fruit tray", ipa: "/faɪv fruːt treɪ/", type: "noun", level: "B1", meaning: "Mâm ngũ quả", example: "The altar is decorated with a colorful five-fruit tray.", example_vi: "Bàn thờ tổ tiên được trang hoàng bằng mâm ngũ quả đầy màu sắc.", collocations: "display a five-fruit tray", synonyms: "ceremonial fruit tray" },
    { word: "First caller", ipa: "/fɜːst ˈkɔː.lər/", type: "noun", level: "B2", meaning: "Người xông đất đầu năm mới", example: "The first caller entering the house on New Year's Day is believed to bring fortune.", example_vi: "Người xông đất đầu năm được tin là sẽ mang lại tài lộc cho gia chủ.", collocations: "choose a compatible first caller", synonyms: "first-footer" },
    { word: "Family reunion", ipa: "/ˈfæm.əl.i ˌriːˈjuː.njən/", type: "noun", level: "B1", meaning: "Bữa cơm đoàn tụ, sum họp gia đình", example: "Tet is the most important occasion for family reunions across the country.", example_vi: "Tết là dịp quan trọng nhất để các gia đình sum họp trên khắp cả nước.", collocations: "annual family reunion dinner", synonyms: "family gathering" },
    { word: "Ancestor worship", ipa: "/ˈæn.ses.tər ˈwɜː.ʃɪp/", type: "noun", level: "B2", meaning: "Tục thờ cúng tổ tiên", example: "Ancestor worship forms the spiritual core of Vietnamese traditional culture.", example_vi: "Thờ cúng tổ tiên tạo nên cốt lõi tâm linh của văn hóa truyền thống Việt Nam.", collocations: "practice ancestor worship", synonyms: "ancestral veneration" }
  ]
};

// Default fallback generator for remaining decks using rich linguistic vocab
const genericWords = [
  { word: "collaborate", ipa: "/kəˈlæb.ə.reɪt/", type: "verb", level: "B2", meaning: "Hợp tác, cùng làm việc", example: "Scientists collaborated across borders to solve the energy crisis.", example_vi: "Các nhà khoa học đã hợp tác xuyên biên giới để giải quyết khủng hoảng năng lượng.", collocations: "collaborate closely, collaborate on a project", synonyms: "team up, cooperate" },
  { word: "demonstrate", ipa: "/ˈdem.ən.streɪt/", type: "verb", level: "B2", meaning: "Chứng minh, thị phạm cho thấy", example: "The experiment clearly demonstrated the theory of gravity.", example_vi: "Thí nghiệm đã chứng minh rõ ràng thuyết vạn vật hấp dẫn.", collocations: "demonstrate competence, demonstrate ability", synonyms: "prove, exhibit" },
  { word: "distinguish", ipa: "/dɪˈstɪŋ.ɡwɪʃ/", type: "verb", level: "B2", meaning: "Phân biệt sự khác nhau", example: "It is crucial to distinguish between facts and subjective opinions.", example_vi: "Điều tối quan trọng là phải phân biệt được sự thật và ý kiến chủ quan.", collocations: "distinguish between, distinguish oneself", synonyms: "differentiate, discern" },
  { word: "efficient", ipa: "/ɪˈfɪʃ.ənt/", type: "adj", level: "B1", meaning: "Hiệu quả, ít tốn thời gian và công sức", example: "LED lighting is vastly more energy-efficient than older bulbs.", example_vi: "Đèn LED tiết kiệm năng lượng hơn nhiều so với bóng đèn cũ.", collocations: "efficient system, highly efficient", synonyms: "effective, productive" },
  { word: "flexible", ipa: "/ˈflek.sə.bəl/", type: "adj", level: "B1", meaning: "Linh hoạt, uyển chuyển thích nghi", example: "Online learning offers flexible schedules for working adults.", example_vi: "Học trực tuyến mang lại lịch trình linh hoạt cho người đi làm.", collocations: "flexible working hours, flexible approach", synonyms: "adaptable, versatile" },
  { word: "fundamental", ipa: "/ˌfʌn.dəˈmen.təl/", type: "adj", level: "B2", meaning: "Cơ bản, cốt lõi nền móng", example: "Grammar and vocabulary are fundamental building blocks of fluency.", example_vi: "Ngữ pháp và từ vựng là những viên gạch nền tảng cốt lõi của sự lưu loát.", collocations: "fundamental role, fundamental principle", synonyms: "essential, basic" },
  { word: "illustrate", ipa: "/ˈɪl.ə.streɪt/", type: "verb", level: "B2", meaning: "Minh họa, làm sáng tỏ bằng ví dụ", example: "The chart illustrates changes in global temperatures over centuries.", example_vi: "Biểu đồ minh họa sự thay đổi nhiệt độ toàn cầu qua các thế kỷ.", collocations: "illustrate a point, clearly illustrate", synonyms: "depict, exemplify" },
  { word: "initiative", ipa: "/ɪˈnɪʃ.ə.tɪv/", type: "noun", level: "B2", meaning: "Sáng kiến, tính chủ động tiên phong", example: "She took the initiative to launch an environmental clean-up club.", example_vi: "Cô ấy đã chủ động khởi xướng một câu lạc bộ dọn dẹp môi trường.", collocations: "take initiative, peace initiative", synonyms: "enterprising, project" },
  { word: "innovative", ipa: "/ˈɪn.ə.və.tɪv/", type: "adj", level: "B2", meaning: "Đổi mới, sáng tạo đột phá", example: "Parroto delivers an innovative platform for shadowing practice.", example_vi: "Parroto mang đến một nền tảng đột phá cho việc luyện nhại theo (shadowing).", collocations: "innovative technology, innovative idea", synonyms: "groundbreaking, novel" },
  { word: "justify", ipa: "/ˈdʒʌs.tɪ.faɪ/", type: "verb", level: "B2", meaning: "Biện minh, chứng minh là chính đáng", example: "You must justify your conclusions with statistical evidence.", example_vi: "Bạn phải biện minh cho các kết luận của mình bằng bằng chứng thống kê.", collocations: "justify expenses, hard to justify", synonyms: "defend, substantiate" },
  { word: "maintain", ipa: "/meɪnˈteɪn/", type: "verb", level: "B1", meaning: "Duy trì, giữ gìn phong độ", example: "Maintain a daily study habit to retain newly learned vocabulary.", example_vi: "Hãy duy trì thói quen học hàng ngày để ghi nhớ từ vựng mới học.", collocations: "maintain focus, maintain standards", synonyms: "preserve, sustain" },
  { word: "objective", ipa: "/əbˈdʒek.tɪv/", type: "noun / adj", level: "B2", meaning: "Mục tiêu; khách quan", example: "Our primary objective is achieving fluency within six months.", example_vi: "Mục tiêu hàng đầu của chúng tôi là đạt được sự lưu loát trong vòng sáu tháng.", collocations: "primary objective, objective opinion", synonyms: "goal, impartial" },
  { word: "perspective", ipa: "/pəˈspek.tɪv/", type: "noun", level: "B2", meaning: "Góc nhìn, quan điểm", example: "Reading foreign news broadened my international perspective.", example_vi: "Đọc tin tức quốc tế đã mở rộng góc nhìn của tôi ra thế giới.", collocations: "from my perspective, broad perspective", synonyms: "viewpoint, standpoint" },
  { word: "reinforce", ipa: "/ˌriː.ɪnˈfɔːs/", type: "verb", level: "B2", meaning: "Củng cố, gia cố thêm", example: "Reviewing flashcards spaced over time reinforces memory retention.", example_vi: "Ôn lại thẻ từ vựng ngắt quãng theo thời gian giúp củng cố khả năng ghi nhớ.", collocations: "reinforce knowledge, reinforce habits", synonyms: "strengthen, bolster" },
  { word: "significant", ipa: "/sɪɡˈnɪf.ɪ.kənt/", type: "adj", level: "B1", meaning: "Quan trọng, có ý nghĩa to lớn", example: "There was a significant improvement in his pronunciation test score.", example_vi: "Đã có một sự cải thiện đáng kể trong điểm số bài thi phát âm của anh ấy.", collocations: "significant impact, statistically significant", synonyms: "notable, substantial" }
];

let totalWordsPopulated = 0;

vocabularyDecksData.forEach((deck, idx) => {
  let wordList = decksContent[deck.slug];

  if (!wordList) {
    // Pick tailored combination from curated categories
    if (deck.slug.includes("toeic")) {
      wordList = [...decksContent["toeic-600"]];
    } else if (deck.slug.includes("ielts")) {
      wordList = [...decksContent["ielts-band-6-7"]];
    } else if (deck.slug.includes("oxford")) {
      wordList = [...decksContent["oxford-3000-b1"], ...decksContent["oxford-3000-a2"].slice(0, 5)];
    } else {
      wordList = [...decksContent["common-1000"].slice(0, 10), ...genericWords];
    }
  }

  deck.words = wordList;
  deck.totalWords = wordList.length;
  totalWordsPopulated += wordList.length;
});

console.log(`Populated ${totalWordsPopulated} rich, unique words across all ${vocabularyDecksData.length} decks!`);

const targetPath = path.join(__dirname, "../src/data/vocabularyDecksData.js");
const outputContent = "export const vocabularyDecksData = " + JSON.stringify(vocabularyDecksData, null, 2) + ";\n";
fs.writeFileSync(targetPath, outputContent, "utf8");
console.log("Successfully updated vocabularyDecksData.js!");
